### PR TITLE
Declare all haptic types

### LINKED ISSUE #14: Define all feedback types for TypeScript
Currently there are only 3 types defined in the ts definition.

### PR DESCRIPTION
**Pull request by krszwsk**
Closes #14.

### CODE REVIEW

**Comment by charlesvinette** [comment]
Merging this in @krszwsk . Thank you very much for your contribution!

**Comment by krszwsk** [comment]
@charlesvinette sure thing, if you could ping me when you publish this to npm, that would be great 🙂.

**Comment by charlesvinette** [comment]
Done deal sir, it's in 1.0.1!

**Comment by krszwsk** [comment]
Thanks!

**Pull request merged**
